### ISSUE TITLE
Firmware Source

### ISSUE THREAD

**Issue by swoopscience** [valkjsaaa/switchmate-firmwares#2]
How/Where are you getting the firmware zips from? I want to maintain a complete archive of future versions...

**Comment by jlippold** [comment]
From a jailbroken iphone, the firmwares are saved in the apps documents location. I saved 3 new firmwares here. https://github.com/jlippold/switchmate-firmwares

**Comment by valkjsaaa** [comment]
You can download the firmware like this:

```
curl -H 'x-api-key: J79FF5JimEacwfg0XvavF1Cxt3WKlGum2YQwYCum' -H 'user-agent: Switchmate/109 CFNetwork/897.9 Darwin/17.5.0' 'https://iot-dev.switchmatehome.com/stage/app-fw/versions/download/bright/2.9.3?' > 2-9-3.zip
```

I get the API key by sniffing the packet that the app send to their server 😈
