### ISSUE TITLE
Latest Bright firmware (2.9.15) works with node-switchmate3 / homebridge-switchmate3

### ISSUE THREAD

**Issue by ronaldheft** [valkjsaaa/switchmate-firmwares#4]
I tested the latest version of the Bright firmware with model TSM003W and everything works with the node-switchmate3 and homebridge-switchmate3 libraries. There were a couple of previous releases between the last known working version (2.9.3) that did not work, but whatever incompatibilities occurred have since been resolved.

If directions are provided in #2, I will be happy to dump the latest firmware, update the documentation, and submit a PR. 😄

**Comment by valkjsaaa** [comment]
Thanks for mentioning that. I have updated the `README.md` accordingly. I've also mentioned how I downloaded the firmware in #2 .
