### ISSUE TITLE
Does not work for original Light?

### ISSUE THREAD

**Issue by Jamie96ITS** [valkjsaaa/switchmate-firmwares#6]
Does anyone know if this works for the original Light? 

I'm trying to downgrade some Light switchmates so I can get Wink compatibility back, and while the app is putting into DFU mode, it just hangs at 0%. The switch "flips" every now and again as the DFU times out, so I know I have the right device selected. Using iOS.

**Comment by valkjsaaa** [comment]
As discussed in https://github.com/brianpeiris/switchmate/issues/6 , they have changed the boot loader at a certain point, so it’s not possible to downgrade to the firmware that support wink hub. Sorry about that.
